---
title: "Coastal Fires Levoglucosan"
author: "RB"
date: "2024-09-13"
output: html_document
---
#load necessary libraries
```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(here)
```

#load data files and rename them
```{r}
CombinedData <- readr::read_csv("CoastalFires_CombinedData.csv")
DischargeData <- readr::read_csv("CoastalFires_Discharge.csv")
``` 
Test data for normality using Shapiro-Wilk Test
```{r}
#are all variables normally distributed?
#filter to only numeric data
numeric_columns <- sapply(CombinedData, is.numeric)
Data_numeric <- CombinedData[, numeric_columns]
Data_numeric <- Data_numeric %>% select(-lat, -long)

# Apply Shapiro-Wilk test and create a readable summary
shapiro_results <- sapply(Data_numeric, function(x) {
  test <- shapiro.test(x)
  return(c(p_value = test$p.value, W = test$statistic))
})

# Convert results to a data frame
shapiro_df <- as.data.frame(t(shapiro_results))
shapiro_df$Variable <- rownames(shapiro_df)
rownames(shapiro_df) <- NULL

# Print readable results
print(shapiro_df)
```
#The differences of concentrations and key ratios by watershed
```{r}
#is the concentration of levoglucosan different across watersheds?
kruskal_test_levo <- kruskal.test(avg_levo_ppb ~ watershed, data = CombinedData)
print(kruskal_test_levo)
#is the ratio of levoglucosan to bulk DOC different across watersheds?
kruskal_test_levotoDOC <- kruskal.test(Levo_DOC_perc ~ watershed, data = CombinedData)
print(kruskal_test_levotoDOC)
#is the ratio of levoglucosan to DBC different across watersheds?
kruskal_test_levotoDBC <- kruskal.test(Levo_DBC ~ watershed, data = CombinedData)
print(kruskal_test_levotoDBC)
```
#Time since fire - Spearman's rank
```{r}
#Ensuring that the Date column is correctly classified as a date rather than a character
CombinedData$date <- as.Date(CombinedData$date, format = "%d-%b-%y")

#Calculating the time since fire for all samples and ensuring it is a numeric value
fire_date <- as.Date("2020-08-16")
CombinedData$time_since_fire_day <- as.numeric(CombinedData$date - fire_date)

#make a table to showcase the coefficients and p-values
# Perform Spearman's rank correlation using the averaged data
spearman_corr_levo_ppb <- cor.test(CombinedData$time_since_fire_day, CombinedData$avg_levo_ppb, method = "spearman", use = "pairwise.complete.obs")

spearman_corr_levoDOC <- cor.test(CombinedData$time_since_fire_day, CombinedData$Levo_DOC_perc, method = "spearman", use = "pairwise.complete.obs")

spearman_corr_DBC_ppm <- cor.test(CombinedData$time_since_fire_day, CombinedData$DBC_mgC_per_L, method = "spearman", use = "pairwise.complete.obs")

spearman_corr_dbcDOC <- cor.test(CombinedData$time_since_fire_day, CombinedData$DBC_DOC_perc, method = "spearman", use = "pairwise.complete.obs")

# Extract p-values and rho values
results <- data.frame(
  Comparison = c("time_since_fire_day vs levo_ppb",
                  "time_since_fire_day vs levoDOC",
                  "time_since_fire_day vs DBC",
                  "time_since_fire_day vs dbcDOC"),
  Rho = c(spearman_corr_levo_ppb$estimate,
          spearman_corr_levoDOC$estimate,
          spearman_corr_DBC_ppm$estimate,
          spearman_corr_dbcDOC$estimate),
  P_Value = c(spearman_corr_levo_ppb$p.value,
              spearman_corr_levoDOC$p.value,
              spearman_corr_DBC_ppm$p.value,
              spearman_corr_dbcDOC$p.value)
)

# Print the results table
print(results)
```
#Miscellaneous Correlation Significant Tests for Levoglucosan
``` {r}
#by burn extent
spearman_corr_BE <- cor.test(CombinedData$Burn_Extent_percent, CombinedData$avg_levo_ppb, method = "spearman", use = "pairwise.complete.obs")
#by low severity burn extent
spearman_corr_BElow <- cor.test(CombinedData$Area_low_severity_percent, CombinedData$avg_levo_ppb, method = "spearman", use = "pairwise.complete.obs")
#by low to moderate severity burn extent
spearman_corr_BElowtomod <- cor.test(CombinedData$Area_low_to_mod_severity_percent, CombinedData$avg_levo_ppb, method = "spearman", use = "pairwise.complete.obs")
#by moderate to high severity burn extent
spearman_corr_BEmodtohigh <- cor.test(CombinedData$Area_mod_to_high_severity_percent, CombinedData$avg_levo_ppb, method = "spearman", use = "pairwise.complete.obs")
#by watershed area
spearman_corr_area <- cor.test(CombinedData$Area_square_kilometer, CombinedData$avg_levo_ppb, method = "spearman", use = "pairwise.complete.obs")
#by watershed slope
spearman_corr_slope <- cor.test(CombinedData$Average_slope_percent, CombinedData$avg_levo_ppb, method = "spearman", use = "pairwise.complete.obs")
#by discharge
spearman_corr_Q <- cor.test(CombinedData$Q_m_sq_per_sec, CombinedData$avg_levo_ppb, method = "spearman", use = "pairwise.complete.obs")

# Extract p-values and rho values
results <- data.frame(
  Comparison = c("avg_levo_ppb vs burn_extent",
                  "avg_levo_ppb vs low burn_extent",
                  "avg_levo_ppb vs low-mod burn_extent",
                 "avg_levo_ppb vs mod-high burn extent", 
                 "avg_levo_ppb vs watershed area", 
                 "avg_levo_ppb vs watershed slope",
                 "avg_levo_ppb vs discharge"),
  Rho = c(spearman_corr_BE$estimate,
          spearman_corr_BElow$estimate,
          spearman_corr_BElowtomod$estimate,
          spearman_corr_BEmodtohigh$estimate,
          spearman_corr_area$estimate,
          spearman_corr_slope$estimate,
          spearman_corr_Q$estimate),
  P_Value = c(spearman_corr_BE$p.value,
              spearman_corr_BElow$p.value,
              spearman_corr_BElowtomod$p.value,
              spearman_corr_BEmodtohigh$p.value,
              spearman_corr_area$p.value,
              spearman_corr_slope$p.value,
              spearman_corr_Q$p.value)
)

# Print the results table
print(results)


```
#Miscellaneous Correlation Significant Tests for Levo:DOC
``` {r}
#by burn extent
spearman_corr_BE <- cor.test(CombinedData$Burn_Extent_percent, CombinedData$Levo_DOC_perc, method = "spearman", use = "pairwise.complete.obs")
#by low severity burn extent
spearman_corr_BElow <- cor.test(CombinedData$Area_low_severity_percent, CombinedData$Levo_DOC_perc, method = "spearman", use = "pairwise.complete.obs")
#by low to moderate severity burn extent
spearman_corr_BElowtomod <- cor.test(CombinedData$Area_low_to_mod_severity_percent, CombinedData$Levo_DOC_perc, method = "spearman", use = "pairwise.complete.obs")
#by moderate to high severity burn extent
spearman_corr_BEmodtohigh <- cor.test(CombinedData$Area_mod_to_high_severity_percent, CombinedData$Levo_DOC_perc, method = "spearman", use = "pairwise.complete.obs")
#by watershed area
spearman_corr_area <- cor.test(CombinedData$Area_square_kilometer, CombinedData$Levo_DOC_perc, method = "spearman", use = "pairwise.complete.obs")
#by watershed slope
spearman_corr_slope <- cor.test(CombinedData$Average_slope_percent, CombinedData$Levo_DOC_perc, method = "spearman", use = "pairwise.complete.obs")
#by discharge
spearman_corr_Q <- cor.test(CombinedData$Q_m_sq_per_sec, CombinedData$Levo_DOC_perc, method = "spearman", use = "pairwise.complete.obs")

# Extract p-values and rho values
results <- data.frame(
  Comparison = c("Levo_DOC_perc vs burn_extent",
                  "Levo_DOC_perc vs low burn_extent",
                  "Levo_DOC_perc vs low-mod burn_extent",
                 "Levo_DOC_perc vs mod-high burn extent", 
                 "Levo_DOC_perc vs watershed area", 
                 "Levo_DOC_perc vs watershed slope",
                 "Levo_DOC_perc vs discharge"),
  Rho = c(spearman_corr_BE$estimate,
          spearman_corr_BElow$estimate,
          spearman_corr_BElowtomod$estimate,
          spearman_corr_BEmodtohigh$estimate,
          spearman_corr_area$estimate,
          spearman_corr_slope$estimate,
          spearman_corr_Q$estimate),
  P_Value = c(spearman_corr_BE$p.value,
              spearman_corr_BElow$p.value,
              spearman_corr_BElowtomod$p.value,
              spearman_corr_BEmodtohigh$p.value,
              spearman_corr_area$p.value,
              spearman_corr_slope$p.value,
              spearman_corr_Q$p.value)
)

# Print the results table
print(results)


```